O-RAN O2 Application in StarlingX
StarlingXWeb/starlingx-website pull request #225
Opened 2023-03-28 12:20 UTC by gaolitao

Add a blogpost for O2 interface feature in StarlingX 8.0

2023-04-19 17:13 UTC, ildikov requested changes
Hi,

Thank you for submitting this blog post to describe the new O-RAN O2 Application in StarlingX. I added a few suggestions in line to correct typos and further polish the text.

Please check my comments and let me know if you have any questions to them.

I'm hoping to publish the blog early next week, once the comments are resolved.

Thanks and Best Regards,
Ildikó

2023-04-19 17:13 UTC, ildikov commented on src/pages/blog/starlingx-oran-o2-application.md
> +- Managing Abstracted Resources and DMSes
```suggestion
- Managing Abstract Resources and DMSs
```

2023-04-19 17:13 UTC, ildikov commented on src/pages/blog/starlingx-oran-o2-application.md
> +  - Creation, Scale-In, Scale-Out of abstracted assigned O-Cloud infrastructure resources
```suggestion
  - Creation, Scale-In, Scale-Out of assigned O-Cloud infrastructure resources
```

2023-04-19 17:13 UTC, ildikov commented on src/pages/blog/starlingx-oran-o2-application.md
> +  - Deployment FCAPS (PM, FM) for abstracted O-Cloud infrastructure resources
```suggestion
  - Deployment of FCAPS components for O-Cloud infrastructure resources
```

2023-04-19 17:13 UTC, ildikov commented on src/pages/blog/starlingx-oran-o2-application.md
> +  - Deployment DMS (Creation, Deletion and Lease of O-Cloud infrastructure)
```suggestion
  - Deployment of DMS (Creation, Deletion and Lease of O-Cloud infrastructure)
```

2023-04-19 17:13 UTC, ildikov commented on src/pages/blog/starlingx-oran-o2-application.md
> +  - Deployment, Termination, Scaling, and Healing of NF & Services deployment resources
```suggestion
  - Deployment, Termination, Scaling, and Healing of NF & Services resources
```

2023-04-19 17:13 UTC, ildikov commented on src/pages/blog/starlingx-oran-o2-application.md
> +  - FCAPS (PM, FM) for NF & Services deployment resources
```suggestion
  - FCAPS, for instance PM and FM, for NF & Services deployment resources
```

2023-04-19 17:13 UTC, ildikov commented on src/pages/blog/starlingx-oran-o2-application.md
> +StarlingX's O-RAN specification compliant O2 interfaces feature is built on top of the[ O2 Service in G release](https://docs.o-ran-sc.org/projects/o-ran-sc-pti-o2/en/g-release/overview.html) of Open
```suggestion
StarlingX's O-RAN specification compliant O2 interfaces feature is built on top of the [O2 Service in G release](https://docs.o-ran-sc.org/projects/o-ran-sc-pti-o2/en/g-release/overview.html) of Open RAN Software Community (ORAN-SC) INF project. At the time of publishing this blog post, the latest version of the compliant specifications are *O-RAN O2ims Interface Specification 3.0* and *O-RAN O2dms Interface Specification: Kubernetes Native API Profile for Containerized NFs 2.0*.
```

2023-04-19 17:13 UTC, ildikov commented on src/pages/blog/starlingx-oran-o2-application.md
> +The O-RAN O2 service is integrated into StarlingX as a system application. With the [StarlingX Application Package Manager](https://docs.starlingx.io/system_configuration/kubernetes/system-configurat
```suggestion
The O-RAN O2 service is integrated into StarlingX as a system application. With the [StarlingX Application Package Manager](https://docs.starlingx.io/system_configuration/kubernetes/system-configuration-starlingx-application-package-manager.html), the O-RAN O2 service application's lifecycle can be managed easily, including managing overrides to the helm charts within the application.
```

2023-04-19 17:13 UTC, ildikov commented on src/pages/blog/starlingx-oran-o2-application.md
> +Please refer to the detailed [procedure for how to install and uninstall O-RAN O2 application in StarlingX](https://docs.starlingx.io/admintasks/kubernetes/oran-o2-application-b50a0c899e66.html).
```suggestion
Please refer to the detailed [procedure for how to install and uninstall the O-RAN O2 application in StarlingX](https://docs.starlingx.io/admintasks/kubernetes/oran-o2-application-b50a0c899e66.html).
```

2023-04-27 17:46 UTC, ildikov approved these changes
This looks great, thank you for updating the post.

I will publish the blog post on Monday in US morning hours.

Thanks and Best Regards,
Ildikó

2023-05-01 14:03 UTC, merged

2023-05-06 06:09 UTC, gaolitao commented
@ildikov  Thank you for merging, seems that the website cannot render the 3rd level of list in https://www.starlingx.io/blog/starlingx-oran-o2-application/

![image](https://user-images.githubusercontent.com/1217042/236604224-b51cd4b7-8811-495c-9cb2-38c85d3a68fe.png)

2023-05-06 15:26 UTC, ildikov commented
@gaolitao Thank you for catching that! I just reached out to our design team to check what the issue might be with the formatting. They're looking into the fix, I'm hoping that it will be corrected early next week.